apiVersion: batch/v1
kind: Job
metadata:
  generateName: pre-sync-
  annotations:
    argocd.argoproj.io/hook: PreSync
  spec:
    template:
      spec:
        containers:
          - name: pre-sync
            image: curlimages/curl
            command:
              - /bin/sh
              - -c
              - |
                curl -X POST -H 'Content-type: application/json' --data '{"text":"Pre-sync hook"}' \
                https://webhook.site/0c480a67-d85f-4011-9446-be4b670ab623
        restartPolicy: Never

