apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo-project
  namespace: argocd
spec:
  description: "Projeto de estudos de ArgoCD"
  sourceRepos:
    - 'https://github.com/Adenilson365/praticando-argocd.git'
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*' 
    # - group: 'apps'
    #   kind: ReplicaSet
    # - group: ''
    #   kind: pod
    # - group: 'autoscaling'
    #   kind: HorizontalPodAutoscaler
    # - group: 'v1'
    #   kind: Service
  roles: 
    - name: pipeline
      policies:
        - p, proj:argo-project:pipeline, applications, get, *, allow
        - p, proj:argo-project:pipeline, applications, list, *, allow
      groups:
        - adenilson
  syncWindows:
    - kind: Allow
      timeZone: America/Sao_Paulo
      schedule: "0 0 * * *"
      duration: "1h0m0s"
      applications:
        - '*'
      clusters: 
        - 'https://kubernetes.default.svc'