apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-wave
  namespace: wave
  labels:
    curso: Devops-Pro
spec:
  project: argo-project
  source:
    repoURL: 'https://github.com/Adenilson365/praticando-argocd.git'
    targetRevision: HEAD
    path: wave
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
      
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: wave


    