apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage
  namespace: webpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
    spec:
      containers:
      - name: webpage
        image: fabricioveronez/pagina-exemplo:green
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "200Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
