# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend
#   labels:
#     istio-metrics: "true"
#   namespace: default
# spec:
#   selector:
#     app: frontend
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
#       name: http

#   type: ClusterIP