apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-web
  namespace: argocd
  labels:
    curso: Devops-Pro
spec:
  project: default
  source:
    repoURL: 'https://github.com/Adenilson365/praticando-argocd.git'
    targetRevision: HEAD
    path: app 
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: webpage
  info:
    - name: "Projeto"
      value: "Estudos de ArgoCD"
    - name: "Descrição"
      value: "Aplicação Web"


    