apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-caos
  namespace: argocd
  labels:
    curso: Devops-Pro
spec:
  project: default
  source:
    repoURL: 'https://github.com/Adenilson365/praticando-argocd.git'
    targetRevision: HEAD
    path: caos 
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: web
      jsonPointers:
        - /spec/replicas
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      name: web
      jsonPointers:
        - status/currentReplicas
        - status/desiredReplicas
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: caos


    